name: build
on:
  push:
    branches: [master]
  pull_request:

env:
  BLS_KEY: ${{ secrets.BLS_KEY }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: "actions/checkout@v4"
        with:
          submodules: recursive

      - name: Install nodejs 🔧
        uses: "actions/setup-node@v3"
        with:
          node-version: 22.3.0

      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build
        
      - name: Test
        run: npm run test
